<a href="https://colab.research.google.com/github/Arif432/yoloDoctor/blob/main/yoloDoctor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [2]:
ROOT_DIR = '/content/gdrive/My Drive/Doctors prescriptions handwriting.v1i.yolov8'

In [3]:
!pip install ultralytics
### 4. Train model ###
import os
from ultralytics import YOLO

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.8/750.8 kB 9.8 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-many

In [6]:
model = YOLO("yolov8m.pt")


100%|██████████| 49.7M/49.7M [00:00<00:00, 255MB/s]


In [7]:
results = model.train(data=os.path.join(ROOT_DIR, "data.yaml"), epochs=15)

Ultralytics YOLOv8.2.1 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8m.pt, data=/content/gdrive/My Drive/Doctors prescriptions handwriting.v1i.yolov8/data.yaml, epochs=15, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save

100%|██████████| 755k/755k [00:00<00:00, 26.2MB/s]


Overriding model.yaml nc=80 with nc=60

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytic

100%|██████████| 6.23M/6.23M [00:00<00:00, 123MB/s]


AMP: checks passed ✅


train: Scanning /content/gdrive/My Drive/Doctors prescriptions handwriting.v1i.yolov8/train/labels.cache... 515 images, 22 backgrounds, 0 corrupt: 100%|██████████| 515/515 [00:00<?, ?it/s]

WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 4173, len(boxes) = 4745. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.


albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
val: Scanning /content/gdrive/My Drive/Doctors prescriptions handwriting.v1i.yolov8/valid/labels.cache... 100 images, 2 backgrounds, 0 corrupt: 100%|██████████| 100/100 [00:00<?, ?it/s]

WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 817, len(boxes) = 950. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.


Plotting labels to runs/detect/train/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000156, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/detect/train
Starting training for 15 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/15      7.37G      2.287       4.95      1.901         35        640: 100%|██████████| 33/33 [00:29<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.01it/s]

                   all        100        950      0.354     0.0646    0.00939    0.00393



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/15      7.47G      1.732      3.562      1.529         49        640: 100%|██████████| 33/33 [00:20<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.14it/s]


                   all        100        950      0.414      0.145     0.0746     0.0418

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/15      7.52G      1.643      3.046      1.495         35        640: 100%|██████████| 33/33 [00:19<00:00,  1.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]


                   all        100        950      0.513      0.173      0.145     0.0853

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/15      7.55G      1.611      2.788      1.477         33        640: 100%|██████████| 33/33 [00:20<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.85it/s]


                   all        100        950      0.378      0.234      0.191       0.11

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/15      7.51G      1.511      2.583      1.431         17        640: 100%|██████████| 33/33 [00:19<00:00,  1.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.12it/s]


                   all        100        950      0.345      0.295      0.237       0.14
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/15      7.49G      1.454      2.298      1.478         24        640: 100%|██████████| 33/33 [00:26<00:00,  1.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]


                   all        100        950      0.482      0.274      0.276      0.171

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/15      7.53G      1.454      2.147      1.507         16        640: 100%|██████████| 33/33 [00:18<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.95it/s]


                   all        100        950      0.506      0.325       0.31      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/15      7.52G      1.377      1.915      1.449         36        640: 100%|██████████| 33/33 [00:18<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.80it/s]


                   all        100        950      0.496      0.353      0.336       0.21

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/15      7.48G       1.32      1.787      1.408         30        640: 100%|██████████| 33/33 [00:18<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.29it/s]


                   all        100        950      0.496      0.363      0.356      0.219

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/15       7.5G      1.295      1.668      1.381         32        640: 100%|██████████| 33/33 [00:18<00:00,  1.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.83it/s]


                   all        100        950       0.53      0.367      0.385      0.243

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/15      7.54G      1.275      1.584      1.372         36        640: 100%|██████████| 33/33 [00:19<00:00,  1.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]


                   all        100        950      0.601      0.371      0.411      0.262

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/15      7.54G      1.259      1.503      1.355         33        640: 100%|██████████| 33/33 [00:18<00:00,  1.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.04it/s]


                   all        100        950      0.588      0.389      0.423      0.263

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/15      7.51G       1.23      1.437      1.345         13        640: 100%|██████████| 33/33 [00:19<00:00,  1.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.98it/s]


                   all        100        950      0.573      0.402      0.423      0.276

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/15      7.53G       1.19      1.371      1.295         24        640: 100%|██████████| 33/33 [00:18<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.23it/s]

                   all        100        950      0.623      0.382      0.445      0.278



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/15      7.59G      1.179      1.319      1.307         33        640: 100%|██████████| 33/33 [00:18<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.91it/s]


                   all        100        950       0.62       0.38      0.474      0.304

15 epochs completed in 0.107 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 52.1MB
Optimizer stripped from runs/detect/train/weights/best.pt, 52.1MB

Validating runs/detect/train/weights/best.pt...
Ultralytics YOLOv8.2.1 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
Model summary (fused): 218 layers, 25874500 parameters, 0 gradients, 78.9 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:08<00:00,  2.16s/it]


                   all        100        950      0.618      0.381      0.474      0.304
                     0        100         52      0.657      0.615      0.607      0.341
                     1        100         14      0.525      0.357      0.536      0.205
                     2        100         23      0.519      0.565      0.551      0.376
                     3        100          2      0.669        0.5      0.586      0.483
                     4        100          6          1          0      0.527      0.419
                     5        100         26      0.706      0.462      0.584      0.385
                     6        100          3          1          0      0.363      0.287
                     7        100          1          1          0      0.995      0.697
                     8        100          3          1          0       0.17      0.136
                     9        100          1          0          0          0          0
                     

In [9]:
model.save()


In [10]:
infer = YOLO("/content/runs/detect/train/weights/best.pt")

In [11]:
infer.predict("/content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images",save=True,save_txt = True)


image 1/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/20230314_201442-5-_jpg.rf.01e0e8cb82ade91a129cadf4b920a3c4.jpg: 640x640 1 a, 1 l, 1 n, 1 o, 43.8ms
image 2/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/20230314_201612-4-_jpg.rf.a45d0c9c55660917301533d51541411b.jpg: 640x640 1 2, 2 5s, 1 a, 1 d, 1 e, 1 g, 2 ns, 2 ss, 59.9ms
image 3/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/274610921_1749841078684575_7548508255602123747_n-5-_jpg.rf.8b0edaba72a4bc627541fbe0bb5d0fc3.jpg: 640x640 1 5, 1 a, 1 e, 1 i, 1 o, 1 t, 1 x, 44.4ms
image 4/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/280119519_1343766579472393_2195751068597739040_n-3-_jpg.rf.0de2956026b338ebb5bfa61edebcefbf.jpg: 640x640 1 0, 1 1, 1 a, 1 o, 1 r, 1 x, 71.7ms
image 5/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/280119519_1343766579472393_21

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: 'A', 11: 'B', 12: 'C', 13: 'D', 14: 'E', 15: 'F', 16: 'G', 17: 'H', 18: 'I', 19: 'K', 20: 'L', 21: 'M', 22: 'N', 23: 'O', 24: 'P', 25: 'Q', 26: 'R', 27: 'S', 28: 'T', 29: 'U', 30: 'V', 31: 'X', 32: 'Y', 33: 'Z', 34: 'a', 35: 'b', 36: 'c', 37: 'd', 38: 'e', 39: 'f', 40: 'g', 41: 'h', 42: 'i', 43: 'j', 44: 'k', 45: 'l', 46: 'm', 47: 'n', 48: 'o', 49: 'p', 50: 'q', 51: 'r', 52: 's', 53: 't', 54: 'u', 55: 'v', 56: 'w', 57: 'x', 58: 'y', 59: 'z'}
 obb: None
 orig_img: array([[[154, 161, 158],
         [154, 161, 158],
         [153, 160, 157],
         ...,
         [143, 152, 149],
         [143, 152, 149],
         [143, 152, 149]],
 
        [[154, 161, 158],
         [154, 161, 158],
         [153, 160, 157],
         ...,
         [143, 152, 149],
         

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
ROOT_DIR = '/content/gdrive/My Drive/Doctors prescriptions handwriting.v1i.yolov8'
import os
from ultralytics import YOLO
model = YOLO("yolov8m.pt")
results = model.train(data=os.path.join(ROOT_DIR, "data.yaml"), epochs=15)


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


100%|██████████| 49.7M/49.7M [00:00<00:00, 140MB/s]


Ultralytics YOLOv8.2.0 🚀 Python-3.10.12 torch-2.2.1+cu121 CPU (Intel Xeon 2.20GHz)
engine/trainer: task=detect, mode=train, model=yolov8m.pt, data=/content/gdrive/My Drive/Doctors prescriptions handwriting.v1i.yolov8/data.yaml, epochs=15, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_c

train: Scanning /content/gdrive/My Drive/Doctors prescriptions handwriting.v1i.yolov8/train/labels.cache... 515 images, 22 backgrounds, 0 corrupt: 100%|██████████| 515/515 [00:00<?, ?it/s]

WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 4173, len(boxes) = 4745. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.


albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/My Drive/Doctors prescriptions handwriting.v1i.yolov8/valid/labels.cache... 100 images, 2 backgrounds, 0 corrupt: 100%|██████████| 100/100 [00:00<?, ?it/s]

WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 817, len(boxes) = 950. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.


Plotting labels to runs/detect/train2/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000156, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs/detect/train2
Starting training for 15 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


  0%|          | 0/33 [00:00<?, ?it/s]

In [ ]:
infer = YOLO("/content/runs/detect/train6/weights/best.pt")
infer.predict("/content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images",save=True,save_txt = True)


image 1/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/20230314_201442-5-_jpg.rf.01e0e8cb82ade91a129cadf4b920a3c4.jpg: 640x640 1 l, 1 o, 37.6ms
image 2/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/20230314_201612-4-_jpg.rf.a45d0c9c55660917301533d51541411b.jpg: 640x640 3 5s, 1 a, 1 d, 1 e, 1 g, 1 n, 37.6ms
image 3/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/274610921_1749841078684575_7548508255602123747_n-5-_jpg.rf.8b0edaba72a4bc627541fbe0bb5d0fc3.jpg: 640x640 1 5, 1 E, 1 a, 1 e, 1 i, 1 t, 1 x, 37.5ms
image 4/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/280119519_1343766579472393_2195751068597739040_n-3-_jpg.rf.0de2956026b338ebb5bfa61edebcefbf.jpg: 640x640 1 0, 1 X, 1 a, 1 o, 1 r, 1 x, 37.6ms
image 5/50 /content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/280119519_1343766579472393_2195751068597739040_n-4-

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: 'A', 11: 'B', 12: 'C', 13: 'D', 14: 'E', 15: 'F', 16: 'G', 17: 'H', 18: 'I', 19: 'K', 20: 'L', 21: 'M', 22: 'N', 23: 'O', 24: 'P', 25: 'Q', 26: 'R', 27: 'S', 28: 'T', 29: 'U', 30: 'V', 31: 'X', 32: 'Y', 33: 'Z', 34: 'a', 35: 'b', 36: 'c', 37: 'd', 38: 'e', 39: 'f', 40: 'g', 41: 'h', 42: 'i', 43: 'j', 44: 'k', 45: 'l', 46: 'm', 47: 'n', 48: 'o', 49: 'p', 50: 'q', 51: 'r', 52: 's', 53: 't', 54: 'u', 55: 'v', 56: 'w', 57: 'x', 58: 'y', 59: 'z'}
 obb: None
 orig_img: array([[[154, 161, 158],
         [154, 161, 158],
         [153, 160, 157],
         ...,
         [143, 152, 149],
         [143, 152, 149],
         [143, 152, 149]],
 
        [[154, 161, 158],
         [154, 161, 158],
         [153, 160, 157],
         ...,
         [143, 152, 149],
         

NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968

In [5]:
import os
import cv2
import numpy as np

# Define the path to the folder containing the images
folder_path = "/content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/train/images"

# Initialize variables to store properties
total_images = 0
image_sizes = []
image_distributions = []

# Iterate through all files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith(".jpg") or filename.endswith(".png"):  # Adjust file extensions as needed
        # Read the image
        image_path = os.path.join(folder_path, filename)
        image = cv2.imread(image_path)

        # Increment total images count
        total_images += 1

        # Get image size
        height, width, _ = image.shape
        image_sizes.append((height, width))

        # Convert image to grayscale for distribution analysis
        grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        # Calculate histogram
        hist = cv2.calcHist([grayscale_image], [0], None, [256], [0, 256])
        # Normalize histogram
        hist /= hist.sum()
        image_distributions.append(hist)

# Calculate total number of images
print("Total images:", total_images)

# Calculate average image size
avg_height = np.mean([size[0] for size in image_sizes])
avg_width = np.mean([size[1] for size in image_sizes])
print("Average image size (height, width):", (avg_height, avg_width))

# Calculate image size distribution
min_height = min([size[0] for size in image_sizes])
max_height = max([size[0] for size in image_sizes])
min_width = min([size[1] for size in image_sizes])
max_width = max([size[1] for size in image_sizes])
print("Minimum image size (height, width):", (min_height, min_width))
print("Maximum image size (height, width):", (max_height, max_width))

# Calculate average image distribution
avg_distribution = np.mean(image_distributions, axis=0)
print("Average image distribution:", avg_distribution)


Total images: 515
Average image size (height, width): (640.0, 640.0)
Minimum image size (height, width): (640, 640)
Maximum image size (height, width): (640, 640)
Average image distribution: [[ 6.9421e-05]
 [ 6.7146e-05]
 [ 6.6074e-05]
 [ 8.0557e-05]
 [ 8.5274e-05]
 [ 8.5103e-05]
 [ 9.2963e-05]
 [ 0.00010509]
 [  0.0001123]
 [ 0.00012295]
 [ 0.00013142]
 [ 0.00014105]
 [ 0.00015456]
 [ 0.00016451]
 [ 0.00018067]
 [ 0.00019205]
 [ 0.00020891]
 [ 0.00022144]
 [  0.0002243]
 [ 0.00023773]
 [ 0.00025064]
 [ 0.00026222]
 [ 0.00026978]
 [ 0.00028008]
 [ 0.00029639]
 [ 0.00030709]
 [ 0.00031892]
 [  0.0003314]
 [ 0.00033482]
 [ 0.00034455]
 [ 0.00034905]
 [  0.0003533]
 [ 0.00036168]
 [  0.0003728]
 [ 0.00037799]
 [  0.0003902]
 [ 0.00039238]
 [ 0.00040289]
 [ 0.00040952]
 [ 0.00041203]
 [ 0.00041981]
 [ 0.00042725]
 [ 0.00042973]
 [ 0.00044137]
 [ 0.00044633]
 [ 0.00044492]
 [ 0.00045619]
 [ 0.00046942]
 [ 0.00047439]
 [ 0.00047393]
 [ 0.00048383]
 [ 0.00048914]
 [ 0.00050193]
 [ 0.00050685]

In [8]:
import os
import cv2
import numpy as np

# Define the path to the folder containing the images
folder_path = "/content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/train/images"

# Initialize variables to store properties
total_images = 0
image_sizes = []
image_distributions = []

# Iterate through all files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith(".jpg") or filename.endswith(".png"):  # Adjust file extensions as needed
        # Read the image
        image_path = os.path.join(folder_path, filename)
        image = cv2.imread(image_path)

        # Print image matrix
        print("Matrix of", filename)
        print(image)

        # Increment total images count
        total_images += 1

        # Get image size
        height, width, _ = image.shape
        image_sizes.append((height, width))

        # Convert image to grayscale for distribution analysis
        grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        # Calculate histogram
        hist = cv2.calcHist([grayscale_image], [0], None, [256], [0, 256])
        # Normalize histogram
        hist /= hist.sum()
        image_distributions.append(hist)

# Calculate total number of images
print("Total images:", total_images)

# Calculate average image size
avg_height = np.mean([size[0] for size in image_sizes])
avg_width = np.mean([size[1] for size in image_sizes])
print("Average image size (height, width):", (avg_height, avg_width))

# Calculate image size distribution
min_height = min([size[0] for size in image_sizes])
max_height = max([size[0] for size in image_sizes])
min_width = min([size[1] for size in image_sizes])
max_width = max([size[1] for size in image_sizes])
print("Minimum image size (height, width):", (min_height, min_width))
print("Maximum image size (height, width):", (max_height, max_width))

# Calculate average image distribution
avg_distribution = np.mean(image_distributions, axis=0)
print("Average image distribution:", avg_distribution)


Streaming output truncated to the last 5000 lines.
  [160 160 160]
  [160 160 160]
  ...
  [167 167 167]
  [167 167 167]
  [167 167 167]]

 [[160 160 160]
  [160 160 160]
  [160 160 160]
  ...
  [167 167 167]
  [167 167 167]
  [167 167 167]]

 ...

 [[160 160 160]
  [160 160 160]
  [160 160 160]
  ...
  [166 166 166]
  [166 166 166]
  [166 166 166]]

 [[160 160 160]
  [160 160 160]
  [160 160 160]
  ...
  [166 166 166]
  [166 166 166]
  [166 166 166]]

 [[160 160 160]
  [160 160 160]
  [160 160 160]
  ...
  [166 166 166]
  [166 166 166]
  [166 166 166]]]
Matrix of 336637521_1270099267260976_3121800169654142318_n-2-_jpg.rf.e206d87cc9175aa74d6a06d620a38d98.jpg
[[[179 181 182]
  [178 180 181]
  [176 178 179]
  ...
  [169 171 171]
  [170 172 172]
  [170 172 172]]

 [[178 180 181]
  [178 180 181]
  [176 178 179]
  ...
  [169 171 171]
  [170 172 172]
  [170 172 172]]

 [[178 180 181]
  [177 179 180]
  [176 178 179]
  ...
  [169 171 171]
  [170 172 172]
  [170 172 172]]

 ...

 [[171 173 174]

In [23]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"
import cv2
import pytesseract

# Define the OCR function
def ocr(image_path):
    # Load image
    image = cv2.imread(image_path)

    # Convert image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Perform OCR using Tesseract
    text = pytesseract.image_to_string(gray)

    return text

# Test the OCR function
image_path = "/content/gdrive/MyDrive/Doctors prescriptions handwriting.v1i.yolov8/test/images/example.jpg"
text = ocr(image_path)
print("Extracted Text:", text)

# ! apt install tesseract-ocr
# ! apt install libtesseract-dev


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 45 not upgraded.
Need to get 4816 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-eng all 1:4.00~git30-7274cfa-1.1 [1591 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-osd all 1:4.00~git30-7274cfa-1.1 [2990 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr amd64 4.1.1-2.1build1 [236 kB]
Fetched 4816 kB in 2s (2922 kB/s)
Selecting previously unselected package tesseract-ocr-eng.
(Reading database ... 121752 files and directories currently installed.)
Preparing to unpack .../tesseract-ocr-eng_1

In [27]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"
# !pip install pytesseract
import cv2
import pytesseract

# Define the OCR function
def ocr(image_path):
    # Load image
    image = cv2.imread(image_path)

    # Convert image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Perform OCR using Tesseract
    text = pytesseract.image_to_string(gray)

    return text

# Test the OCR function
image_path = "/content/runs/detect/predict/20230314_201442-5-_jpg.rf.01e0e8cb82ade91a129cadf4b920a3c4.jpg"
text = ocr(image_path)
print("Extracted Text:", text)

# ! apt install tesseract-ocr
# ! apt install libtesseract-dev


Extracted Text:  

